import { createContext, useContext, useState } from 'react';

export const translations = {
    en: {
        nav: {
            home: 'Home', map: 'Risk Map', dashboard: 'Dashboard',
            report: 'Report Issue', admin: 'Admin', awareness: 'Awareness',
        },
        home: {
            badge: 'Solving SDG 6: Clean Water & Sanitation',
            heroTitle: 'Safeguarding Every Drop with',
            heroSub: 'Artificial Intelligence',
            heroDesc: 'AquaGuardian is a startup-grade platform that combines IoT sensor integration, community crowdsourcing, and predictive AI to map, monitor, and manage the world\'s most precious resource.',
            viewMap: 'View Live Map',
            reportIssue: 'Report an Issue',
            crisisTitle: 'The Global Water Crisis',
            crisisDesc: 'Clean water is a human right, yet billions suffer from lack of access and unsafe sanitation.',
            solutionTag: 'The Solution',
            solutionTitle: 'Everything you need to manage water ecosystems',
            guardianTitle: 'Citizen',
            guardianTitleAccent: 'Guardians',
            guardianDesc: 'Our platform rewards community action. By reporting leaks and monitoring quality, these top guardians have saved thousands of liters of fresh water this month.',
            impactLabel: 'Total Community Impact',
            litersSaved: 'Liters Saved Today',
            leaksFixed: 'Leaks Fixed',
            citizens: 'Citizens Active',
            ctaTitle: 'Ready to make an impact?',
            ctaDesc: 'Join local authorities, NGOs, and communities worldwide in utilizing AquaGuardian to secure a sustainable future for water resources.',
            openDashboard: 'Open Analytics Dashboard',
        },
        map: {
            networkTitle: 'South India Network',
            networkDesc: 'Monitoring 100+ active IoT nodes across the region.',
            heatmap: 'Heatmap',
            markers: 'Markers',
            legend: 'Legend',
            safe: 'Safe',
            warning: 'Warning',
            danger: 'Danger',
        },
        dashboard: {
            title: 'Analytics Dashboard',
            subtitle: 'Real-time water quality metrics and AI-driven risk models.',
            exportCSV: 'Export CSV',
            avgPh: 'Average pH',
            risk: 'Contamination Risk',
            usage: 'Water Usage (L)',
            sensors: 'Sensors Online',
            qualityTrend: 'Water Quality Trend',
            aiForecast: 'AI Contamination Forecast',
            aiSubtitle: 'Predictive analysis for the next 7 days',
        },
        report: {
            title: 'Report an Issue',
            desc: 'Help your community by reporting water leaks, contamination, or sanitation failures. Your reports are directly routed to municipal authorities for rapid response.',
            issueType: 'Issue Type',
            location: 'Location (Auto-detected)',
            description: 'Description',
            descPlaceholder: 'Please describe the issue in detail...',
            photoEvidence: 'Photo Evidence',
            upload: 'Click to upload or drag and drop',
            uploadSub: 'SVG, PNG, JPG or MP4 (max. 10MB)',
            submit: 'Submit Report',
            submitting: 'Submitting...',
            successTitle: 'Report Submitted Successfully',
            successDesc: 'Thank you! Your report has been logged and authorities have been notified.',
            submitAnother: 'Submit Another Report',
            pointsEarned: 'Guardian Points Earned!',
            pointsDesc: '+50 points added to your Guardian profile',
            leaderboard: 'Guardian Leaderboard',
        },
        chatbot: {
            title: 'AquaBot',
            subtitle: 'AI Water Quality Assistant',
            placeholder: 'Ask about water quality...',
            greeting: 'Hi! I\'m AquaBot 🌊 Ask me anything about water quality, contamination risks, or how to report issues.',
        },
    },
    te: {
        nav: {
            home: 'హోమ్', map: 'రిస్క్ మ్యాప్', dashboard: 'డాష్‌బోర్డ్',
            report: 'సమస్య నివేదించు', admin: 'అడ్మిన్', awareness: 'అవగాహన',
        },
        home: {
            badge: 'SDG 6 పరిష్కారం: స్వచ్ఛ నీరు & పారిశుద్ధ్యం',
            heroTitle: 'ప్రతి నీటి చుక్కను రక్షించడం',
            heroSub: 'కృత్రిమ మేధస్సుతో',
            heroDesc: 'AquaGuardian అనేది IoT సెన్సార్ ఇంటిగ్రేషన్, సమాజ క్రౌడ్‌సోర్సింగ్, మరియు AI ని ఒకచోట చేర్చే ప్లాట్‌ఫారమ్.',
            viewMap: 'లైవ్ మ్యాప్ చూడండి',
            reportIssue: 'సమస్యను నివేదించండి',
            crisisTitle: 'ప్రపంచ నీటి సంక్షోభం',
            crisisDesc: 'స్వచ్ఛ నీరు మానవ హక్కు, అయినా కోట్లాది మంది సురక్షిత నీరు లేకుండా బాధపడుతున్నారు.',
            solutionTag: 'పరిష్కారం',
            solutionTitle: 'నీటి పర్యావరణ వ్యవస్థలను నిర్వహించడానికి అన్నీ',
            guardianTitle: 'పౌర',
            guardianTitleAccent: 'సంరక్షకులు',
            guardianDesc: 'మన ప్లాట్‌ఫారమ్ సమాజ చర్యలను ప్రోత్సహిస్తుంది. నివేదించడం ద్వారా వేల లీటర్ల నీటిని ఆదా చేశారు.',
            impactLabel: 'మొత్తం సమాజ ప్రభావం',
            litersSaved: 'ఈ రోజు ఆదా అయిన లీటర్లు',
            leaksFixed: 'లీకేజీలు పరిష్కరించబడ్డాయి',
            citizens: 'చురుకైన పౌరులు',
            ctaTitle: 'ప్రభావం చూపించడానికి సిద్ధంగా ఉన్నారా?',
            ctaDesc: 'స్థానిక అధికారులు, NGOలు మరియు ప్రపంచ సమాజాలతో చేరండి.',
            openDashboard: 'అనలిటిక్స్ డాష్‌బోర్డ్ తెరవండి',
        },
        map: {
            networkTitle: 'దక్షిణ భారత నెట్‌వర్క్',
            networkDesc: 'ప్రాంతమంతటా 100+ IoT నోడ్‌లు పర్యవేక్షిస్తున్నాయి.',
            heatmap: 'హీట్‌మ్యాప్',
            markers: 'మార్కర్లు',
            legend: 'గుర్తు',
            safe: 'సురక్షితం',
            warning: 'హెచ్చరిక',
            danger: 'ప్రమాదం',
        },
        dashboard: {
            title: 'అనలిటిక్స్ డాష్‌బోర్డ్',
            subtitle: 'రియల్-టైమ్ నీటి నాణ్యత మెట్రిక్స్ మరియు AI రిస్క్ మోడల్స్.',
            exportCSV: 'CSV ఎగుమతి',
            avgPh: 'సగటు pH',
            risk: 'కాలుష్య ప్రమాదం',
            usage: 'నీటి వినియోగం (L)',
            sensors: 'సెన్సార్లు ఆన్‌లైన్',
            qualityTrend: 'నీటి నాణ్యత ట్రెండ్',
            aiForecast: 'AI కాలుష్య అంచనా',
            aiSubtitle: 'తదుపరి 7 రోజుల అంచనా విశ్లేషణ',
        },
        report: {
            title: 'సమస్యను నివేదించండి',
            desc: 'నీటి లీకేజీలు, కాలుష్యం లేదా పారిశుద్ధ్య వైఫల్యాలను నివేదించడం ద్వారా మీ సమాజానికి సహాయపడండి.',
            issueType: 'సమస్య రకం',
            location: 'స్థానం (స్వయంచాలకంగా గుర్తించబడింది)',
            description: 'వివరణ',
            descPlaceholder: 'దయచేసి సమస్యను వివరంగా వివరించండి...',
            photoEvidence: 'ఫోటో ఆధారం',
            upload: 'అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
            uploadSub: 'SVG, PNG, JPG లేదా MP4 (గరిష్ఠ. 10MB)',
            submit: 'నివేదిక సమర్పించండి',
            submitting: 'సమర్పిస్తోంది...',
            successTitle: 'నివేదిక విజయంగా సమర్పించబడింది',
            successDesc: 'ధన్యవాదాలు! మీ నివేదిక నమోదు చేయబడింది.',
            submitAnother: 'మరొక నివేదిక సమర్పించండి',
            pointsEarned: 'గార్డియన్ పాయింట్లు సంపాదించారు!',
            pointsDesc: '+50 పాయింట్లు మీ గార్డియన్ ప్రొఫైల్‌కు జోడించబడ్డాయి',
            leaderboard: 'గార్డియన్ లీడర్‌బోర్డ్',
        },
        chatbot: {
            title: 'AquaBot',
            subtitle: 'AI నీటి నాణ్యత సహాయకుడు',
            placeholder: 'నీటి నాణ్యత గురించి అడగండి...',
            greeting: 'నమస్కారం! నేను AquaBot 🌊 నీటి నాణ్యత, కాలుష్య ప్రమాదాలు గురించి అడగండి.',
        },
    },
    hi: {
        nav: {
            home: 'होम', map: 'जोखिम नक्शा', dashboard: 'डैशबोर्ड',
            report: 'समस्या रिपोर्ट करें', admin: 'एडमिन', awareness: 'जागरूकता',
        },
        home: {
            badge: 'SDG 6 समाधान: स्वच्छ जल और स्वच्छता',
            heroTitle: 'हर बूंद की सुरक्षा',
            heroSub: 'कृत्रिम बुद्धिमत्ता के साथ',
            heroDesc: 'AquaGuardian एक प्लेटफ़ॉर्म है जो IoT सेंसर, सामुदायिक क्राउडसोर्सिंग, और AI को जोड़ता है।',
            viewMap: 'लाइव मानचित्र देखें',
            reportIssue: 'समस्या रिपोर्ट करें',
            crisisTitle: 'वैश्विक जल संकट',
            crisisDesc: 'स्वच्छ जल एक मानव अधिकार है, फिर भी अरबों लोग सुरक्षित जल तक पहुंच के बिना पीड़ित हैं।',
            solutionTag: 'समाधान',
            solutionTitle: 'जल पारिस्थितिकी तंत्र प्रबंधन के लिए सब कुछ',
            guardianTitle: 'नागरिक',
            guardianTitleAccent: 'संरक्षक',
            guardianDesc: 'हमारा प्लेटफ़ॉर्म सामुदायिक कार्रवाई को पुरस्कृत करता है। रिपोर्ट करके हजारों लीटर पानी बचाया।',
            impactLabel: 'कुल सामुदायिक प्रभाव',
            litersSaved: 'आज बचाए गए लीटर',
            leaksFixed: 'लीकेज ठीक किए गए',
            citizens: 'सक्रिय नागरिक',
            ctaTitle: 'प्रभाव डालने के लिए तैयार हैं?',
            ctaDesc: 'स्थानीय अधिकारियों, NGOs और दुनिया भर के समुदायों के साथ जुड़ें।',
            openDashboard: 'एनालिटिक्स डैशबोर्ड खोलें',
        },
        map: {
            networkTitle: 'दक्षिण भारत नेटवर्क',
            networkDesc: 'पूरे क्षेत्र में 100+ IoT नोड्स की निगरानी।',
            heatmap: 'हीटमैप',
            markers: 'मार्कर',
            legend: 'किंवदंती',
            safe: 'सुरक्षित',
            warning: 'चेतावनी',
            danger: 'खतरा',
        },
        dashboard: {
            title: 'एनालिटिक्स डैशबोर्ड',
            subtitle: 'रियल-टाइम जल गुणवत्ता मेट्रिक्स और AI जोखिम मॉडल।',
            exportCSV: 'CSV निर्यात करें',
            avgPh: 'औसत pH',
            risk: 'संदूषण जोखिम',
            usage: 'जल उपयोग (L)',
            sensors: 'सेंसर ऑनलाइन',
            qualityTrend: 'जल गुणवत्ता प्रवृत्ति',
            aiForecast: 'AI संदूषण पूर्वानुमान',
            aiSubtitle: 'अगले 7 दिनों के लिए भविष्यवाणी विश्लेषण',
        },
        report: {
            title: 'समस्या रिपोर्ट करें',
            desc: 'पानी की लीकेज, प्रदूषण, या स्वच्छता विफलताओं की रिपोर्ट करके अपने समुदाय की मदद करें।',
            issueType: 'समस्या प्रकार',
            location: 'स्थान (स्वतः पता लगाया गया)',
            description: 'विवरण',
            descPlaceholder: 'कृपया समस्या का विस्तार से वर्णन करें...',
            photoEvidence: 'फोटो प्रमाण',
            upload: 'अपलोड करने के लिए क्लिक करें',
            uploadSub: 'SVG, PNG, JPG या MP4 (अधिकतम 10MB)',
            submit: 'रिपोर्ट सबमिट करें',
            submitting: 'सबमिट हो रहा है...',
            successTitle: 'रिपोर्ट सफलतापूर्वक सबमिट की गई',
            successDesc: 'धन्यवाद! आपकी रिपोर्ट दर्ज कर ली गई है।',
            submitAnother: 'एक और रिपोर्ट सबमिट करें',
            pointsEarned: 'गार्डियन पॉइंट अर्जित!',
            pointsDesc: '+50 पॉइंट आपकी गार्डियन प्रोफ़ाइल में जोड़े गए',
            leaderboard: 'गार्डियन लीडरबोर्ड',
        },
        chatbot: {
            title: 'AquaBot',
            subtitle: 'AI जल गुणवत्ता सहायक',
            placeholder: 'जल गुणवत्ता के बारे में पूछें...',
            greeting: 'नमस्ते! मैं AquaBot हूं 🌊 जल गुणवत्ता, प्रदूषण जोखिम के बारे में पूछें।',
        },
    },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');
    const t = translations[lang] || translations['en'];
    const setLanguage = (l) => {
        setLang(l);
        localStorage.setItem('lang', l);
    };
    return (
        <LanguageContext.Provider value={{ lang, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
